sudo: false
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - uuid-dev
language: node_js
node_js:
- '8'
- '7'
env:
  global:
  - CXX=g++-4.9
  - CC=gcc-4.9
  matrix:
  - ZMQ="4.1.6" ZMQ_REPO="zeromq4-1"
services:
- mysql
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mariadb && mysql.server start; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zeromq; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=/usr/bin/clang; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=/usr/bin/clang++; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ldlocal; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LDHACK=`pwd`/ldlocal; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_RUN_PATH=$LDHACK/lib; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=$LDHACK/lib; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/zeromq/$ZMQ_REPO/releases/download/v$ZMQ/zeromq-$ZMQ.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf zeromq-$ZMQ.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd zeromq-$ZMQ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix=$LDHACK --without-libsodium; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j install; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi
- mysql -uroot -e 'CREATE DATABASE INFOLOGGER;'
before_script:
- npm install -g codecov
- openssl req -new  -newkey rsa:2048 -days 365 -nodes -x509 -subj "/C=CH/ST=Test/L=Test/O=Tst/CN=localhost" -keyout test.key -out test.pem
- mv config-default.json config.json
script: npm test
after_success:
- npm run coverage
- ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
notifications:
  email: false
  slack:
    secure: mmn5dhsQ78Ak+d5GrT52G6SUqklTXp0Dl+rpsrSIMubSxKQmRtrU/KkSjVNP39+LllvwYVHNOZPVti6LYXD9Yq3ZAtipkLuZKqypTa8QdoBsYWVsN+8upQr1ywEbH+88QriFALZIFZz4wGwtentKFPWdUerpuK3r85MQmlxfirz+pRmmpsI2z4XfnfSc0lXphXX2czWCwt/wVotOUITn44ZqVdaZksjp2pXvvmqMXdt7HcVDVzigTRI7W8s9Mfsh8CYHVI6W9z7FSblb/tCA7MoaMhKjE2myA6cEocmj1FfXAvPY4VLDLoJk7c80y1RkxIsofip3fNyzSzqAkC7hLfUROYbNLXuJ0jLiK/7Benl21BHiP9Me23UIETr4SZC0li8mLkqYHMWzzGMPODpHj5e1zYtRCfw5XXxtjtyVSAO4oTZC5BjvQxEo+xAZZLdv65O4g94dqpQsEKSbAPiHUguIjQRxql4DBzIEVFrd0KpdxG8vBdB272b5x+WyGBagKU2HypnakwMGVQwM4WfwD3PWb8ZM+n314d51faypgvTQmZge98TI8m7z6D3B42+Yza/tKetkK/vFPWsO+QunUqMswxUs1RhBSX8wMFFFYx8GKzJYKziQbF0jvDWU+rUmPy68hXZGgLuqNIwACez7jcxz5lHkQAkI4q4H4SLKgoo=
