sudo: false
os:
- linux
- osx
language: node_js
node_js:
- '8'
env:
  matrix:
  - ZMQ="4.1.6" ZMQ_REPO="zeromq4-1"
  global:
    secure: OKr88noh18pgB40M6vT1rxd+rIE4HUhdtsqbT5fKG3z8alXcwsEwepwRBDCZ1or/iEbOwisJqf+k/p1hQMuT3RKe2G7uwtHQZD2UvB8F3H1ScyA+2QC1wzEbKXxMJ7BE076vTJ5t4tdu/eiK/AKmZCc5XUHSTSG1s8DkA3KMqLSVALo4BfITpYAMTgmlvkQx5c/uOHl5BubszasgKTyGVM1qIRa2yC0ADdtJVS/oRWYSOvFwJJsgoyZ2Veob0DE0BWmbxH6FbMb/ccRDfXnfOeEp1Wj6N059t7w6veN1YbA6CBI4uDBXEaoknFeqfhIKz0kgewJd9xMz4EjAoIcwx5TbyJNsXPd0tt/vHVBZwLMPVWldFMHZrdyP1hxZjkH91yCQX4neYQS8aBX4wya4n2tOYy3ArRWJQjyrq9L9nTY6bbjubMTA4H5G3pl1cQJk1aeyElteb37DpG9c7TMOY4HdgUQ6JHJEXLKY2rwr680H5GwAgjZnnFAwSqeHUDPTNMEa81dmA9W35bkBRq9JSSqVbVOafZyFaDwq99sJa9N7UbnBjZgVip1OOGpk+vSEob/yDs6s/5nMQv/6Wvev9aWpP0AZKmPDjupukMc1caIY1ap8c4ZH5FjT0Bgq6M2XtECwnqpDdzIHRDVqU30UBUACwrEJuiN+w8U2HWE7UvM=
services:
- mysql
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mariadb && mysql.server start; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zeromq; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=/usr/bin/clang; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=/usr/bin/clang++; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ldlocal; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LDHACK=`pwd`/ldlocal; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_RUN_PATH=$LDHACK/lib; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=$LDHACK/lib; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/zeromq/$ZMQ_REPO/releases/download/v$ZMQ/zeromq-$ZMQ.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf zeromq-$ZMQ.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd zeromq-$ZMQ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix=$LDHACK --without-libsodium; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j install; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi
- mysql -uroot -e 'CREATE DATABASE INFOLOGGER;'
before_script:
- npm install -g codecov nyc jsdoc-to-markdown
- cd Backend; openssl req -new  -newkey rsa:2048 -days 365 -nodes -x509 -subj "/C=CH/ST=Test/L=Test/O=Tst/CN=localhost" -keyout test.key -out test.pem
- cd Backend; mv config-default.json config.json
- cd Backend; rm test/mocha-ws.js
script: npm test
after_success:
- nyc ./node_modules/mocha/bin/mocha Backend/test
- nyc report --reporter=text-lcov > coverage.lcov && codecov
- cd Backend; jsdoc2md --files ./*.js http/*.js jwt/*.js public/*.js websocket/*.js zeromq/*.js test/*.js db/*.js log/*.js > docs/API.md
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git add docs/API.md && git commit -m "Travis auto generated JSDoc ($TRAVIS_BUILD_NUMBER)" && git push origin $TRAVIS_PULL_REQUEST_BRANCH; fi
notifications:
  email: false
  slack:
    secure: mmn5dhsQ78Ak+d5GrT52G6SUqklTXp0Dl+rpsrSIMubSxKQmRtrU/KkSjVNP39+LllvwYVHNOZPVti6LYXD9Yq3ZAtipkLuZKqypTa8QdoBsYWVsN+8upQr1ywEbH+88QriFALZIFZz4wGwtentKFPWdUerpuK3r85MQmlxfirz+pRmmpsI2z4XfnfSc0lXphXX2czWCwt/wVotOUITn44ZqVdaZksjp2pXvvmqMXdt7HcVDVzigTRI7W8s9Mfsh8CYHVI6W9z7FSblb/tCA7MoaMhKjE2myA6cEocmj1FfXAvPY4VLDLoJk7c80y1RkxIsofip3fNyzSzqAkC7hLfUROYbNLXuJ0jLiK/7Benl21BHiP9Me23UIETr4SZC0li8mLkqYHMWzzGMPODpHj5e1zYtRCfw5XXxtjtyVSAO4oTZC5BjvQxEo+xAZZLdv65O4g94dqpQsEKSbAPiHUguIjQRxql4DBzIEVFrd0KpdxG8vBdB272b5x+WyGBagKU2HypnakwMGVQwM4WfwD3PWb8ZM+n314d51faypgvTQmZge98TI8m7z6D3B42+Yza/tKetkK/vFPWsO+QunUqMswxUs1RhBSX8wMFFFYx8GKzJYKziQbF0jvDWU+rUmPy68hXZGgLuqNIwACez7jcxz5lHkQAkI4q4H4SLKgoo=
