coverage:
  precision: 2
  round: nearest
  range: 60...90
  status:
    project:
      default: off
      Framework:
        target: 50
        flags:
          - framework 
        threshold: 0
        if_not_found: success
      QualityControl:
        target: 60
        flags:
          - qualitycontrol
        threshold: 0
        if_not_found: success
      InfoLogger:
        target: 70
        flags:
          - infologger
        threshold: 0
        if_not_found: success
      Control:
        target: 69
        flags:
          - control
        threshold: 0
        if_not_found: success
    patch: false
    changes: false
    threshold: 0

flags:
  control:
    paths:
      - Control
  qualitycontrol:
    paths:
      - QualityControl
  infologger:
    paths:
      - InfoLogger
  framework:
    paths:
      - Framework
ignore:
  - docs/*
  - node_modules/*

comment: false
