codecov:
  notify:
    after_n_builds: 2
coverage:
  precision: 2
  round: nearest
  range: 60...90
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_not_found: success
        if_ci_error: error
ignore:
  - docs/*
  - node_modules/*
comment: false
