codecov:
  notify:
    after_n_builds: 1
coverage:
  range: 70...90
  precision: 2
  round: nearest
  status:
    project:
      default: 
        target: 80%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
      Control:
        target: 90%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "Control"
      QualityControl:
        target: 91%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "QualityControl"
      InfoLogger:
        target: 92%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "InfoLogger"
      Framework:
        target: 95%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "Framework"
    patch: false
ignore:
  - docs/*
  - node_modules/*
comment: false
