codecov:
  notify:
    after_n_builds: 1
coverage:
  range: 50...80
  precision: 2
  round: nearest
  status:
    project:
      default: false
      Control:
        target: 70%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "Control"
      QualityControl:
        target: 60%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "QualityControl"
      InfoLogger:
        target: 70%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        paths: 
          - "InfoLogger"
      Framework:
        flags:
          - framework
        target: 50%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
       
    patch: false
flags:
  framework:
    paths: 
      - "Framework" 
ignore:
  - docs/*
  - node_modules/*
comment: false
