codecov:
  notify:
    after_n_builds: 1
coverage:
  range: 70...90
  precision: 2
  round: nearest
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
    patch: false
ignore:
  - docs/*
  - node_modules/*
comment: false
