codecov:
  notify:
    after_n_builds: 2

coverage:
  precision: 2
  round: nearest
  range: 50...90
  status:
    project: true
    patch: true
    target: 80
    changes: false
    threshold: 0

ignore:
  - docs/*
  - node_modules/*

comment: false
