codecov:
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: nearest
  range: 70...90
  status:
    project: 
      default: false
      framework:
        target: 90%
        paths: "Framework/Backend/test"
    patch: true
    target: 80
    changes: false
    threshold: 0

ignore:
  - docs/*
  - node_modules/*

comment: false
