codecov:
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: nearest
  range: 70...90
  status:
    project: 
      default: false
      Framework:
        target: 50%
        flags: Framework
      QualityControl:
        flags: QualityControl
        target: 40%
      InfoLogger:
        flags: InfoLogger
        target: 70%
      Control:
        flags: Control
        target: 70%
    patch: true
    target: 80
    changes: false
    threshold: 0

flags:
  Framework:
    paths: "Framework/Backend"
  QualityControl:
    paths: "QualityControl"
  InfoLogger:
    paths: "InfoLogger"
  Control:
    paths: "Control"

ignore:
  - docs/*
  - node_modules/*

comment: false
