codecov:
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: nearest
  range: 70...90
  status:
    project: 
      default: false
      Framework:
        target: 90%
        paths: "Framework/Backend"
        threshold: null
      QualityControl:
        paths: "QualityControl"
        threshold: null
      InfoLogger:
        paths: "InfoLogger"
        threshold: null
      Control:
        paths: "Control"
        threshold: null
    patch: true
    changes: false
    threshold: 0

ignore:
  - docs/*
  - node_modules/*

comment: false
