name: Control
on:
  pull_request:
    paths:
      - 'Control/*'
      - 'Control/*/*'
      - 'Control/*/*/*'
      - '.github/workflows/control.yml'
  push:
    branches:
      - 'master'
      - 'dev'

jobs:
  test:
    name: Tests on macos-latest
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: (cd Control; npm ci )
      - run: (cd Control; npm test )
  coverage:
    name: Tests & coverage on ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: (cd Control; npm ci )
      - run: (cd Control; npm run coverage )
      - run: (cd Control; ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov)
      - name: Codecov
        uses: codecov/codecov-action@v1.0.6
        flags: control