name: Framework

on:
  pull_request:
    paths:
      - 'Framework/*'
      - 'Framework/*/*'
      - 'Framework/*/*/*'
      - '.github/workflows/framework.yml'
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '*'
jobs:
  compatibility:
    name: Test all GUIs with Framework changes
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this PR
        uses: actions/checkout@v2
        with:
          path: WebUI-current
      - name: Checkout WebUI dev
        uses: actions/checkout@v2
        with:
          ref: dev
          path: WebUI-dev
    - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
    - run: (cd $GITHUB_WORKSPACE/WebUI-current/Framework/; npm i)
    - run: (cd $GITHUB_WORKSPACE/WebUI-dev/InfoLogger; npm i)
    - run: rm -rf $GITHUB_WORKSPACE/WebUI-dev/InfoLogger/node_modules/@aliceo2/web-ui
    - run: ln -s $GITHUB_WORKSPACE/WebUI-current/Framework $GITHUB_WORKSPACE/WebUI-dev/InfoLogger/node_modules/@aliceo2/web-ui
    - run: (cd $GITHUB_WORKSPACE/WebUI-dev/InfoLogger; npm test)
