name: Framework-Compatibility
on:
  pull_request:
    paths:
      - 'Framework/*'
      - 'Framework/*/*'
      - 'Framework/*/*/*'
      - '.github/workflows/framework.yml'

jobs:
  control-compatibility:
    name: Control compatibility test 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04]
    steps:
      - name: Run Control tests by using `@aliceo2/web-ui` from local `../Framework`
        run : (echo "Run Control tests by using @aliceo2/web-ui from local ../Framework";) 
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: (cd Control; npm i)
      - name: Check @aliceo2/web-ui was successfully linked locally
        run: (cd Control; if [[ -z $(npm list @aliceo2/web-ui --link | grep @aliceo2/web-ui) ]]; then exit 1; else echo "@aliceo2/web-ui successfully linked"; fi;)
      - run: (cd Control; npm test )