name: Framework-Compatibility
on:
  pull_request:
    paths:
      - 'Framework/*'
      - 'Framework/*/*'
      - 'Framework/*/*/*'
      - '.github/workflows/framework.yml'

jobs:
  control-compatibility:
    name: Control compatibility test 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04]
    steps:
      - name: Run Control tests by using local Framework project
        run : (echo "Run Control tests by using local Framework project";) 
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: (cd Control; npm i)
      - run: (cd Control; npm i --save ../Framework)
      - name: Check @aliceo2/web-ui was successfully linked locally
        run: ([[ -z $(npm list @aliceo2/web-ui --link | grep @aliceo2/web-ui) ]] && exit 1;)
      - run: (cd Control; npm test )