name: Framework

on:
  push:
    paths:
      - 'Framework/*'
      - 'Framework/*/*'
      - 'Framework/*/*/*'
      - '.github/workflows/framework.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: (cd Framework/Backend; openssl req -new  -newkey rsa:2048 -days 365 -nodes -x509 -subj "/C=CH/ST=Test/L=Test/O=Tst/CN=localhost" -keyout test.key -out test.pem)
      - run: (cd Framework/Backend/test; rm mocha-ws.js; sed -i -e 's/const skip = true/const skip = false/g' mocha-db.js)
      - run: (cd Framework; npm install )
      - run: (cd Framework; npm test )
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: (cd Framework; npm install )
      - run: (cd Framework; npm run coverage )
      - run: (cd Framework; ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: Framework/coverage.lcov
