name: InfoLogger

on:
  push:
    paths:
      - 'InfoLogger/*'
      - 'InfoLogger/*/*'
      - 'InfoLogger/*/*/*'
      - '.github/workflows/control.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: (cd InfoLogger; npm install )
      - run: (cd InfoLogger; npm test )
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: (cd InfoLogger; npm install )
      - run: (cd InfoLogger; npm run coverage )
      - run: (cd InfoLogger; ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: InfoLogger/coverage.lcov
