name: QualityControl

on:
  push:
    paths:
      - 'QualityControl/*'
      - 'QualityControl/*/*'
      - 'QualityControl/*/*/*'
      - '.github/workflows/qc.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: (cd QualityControl; sed -i -e "s/require('..\/build\/Release\/tobject2json.node')/null/g" lib/TObject2JsonClient.js)
      - run: (cd QualityControl; npm install )
      - run: (cd QualityControl; npm test )
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: (cd QualityControl; sed -i -e "s/require('..\/build\/Release\/tobject2json.node')/null/g" lib/TObject2JsonClient.js)
      - run: (cd QualityControl; npm install )
      - run: (cd QualityControl; npm run coverage )
      - run: (cd QualityControl; ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: QualityControl/coverage.lcov
