name: Node.js Package
on:
  release:
    types: [created]
jobs:
  deploy-npm-module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Set variable TAG as name of project that is being released
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/aliceo2\//}
    - name: Set variable TAG as name of project that is being released
      run: echo ${GITHUB_REF/refs\/tags\/aliceo2\//}

